# Generated by Django 4.2 on 2023-04-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fspru', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VerifyUsers',
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AlterField(
            model_name='events',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='contest_imgs/'),
        ),
        migrations.AlterField(
            model_name='users',
            name='login_email',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
